version: '3.7'

services:
    php:
        build:
            context: .
            target: dev
        environment:
            COMPOSER_HOME: /home/docker/.composer
            PHP_IDE_CONFIG: 'serverName=circleci-api-client'
            XDEBUG_MODE: '${XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: 'client_host=172.17.0.1'
            XDEBUG_SESSION: 'circleci-api-client'
        volumes:
            - ./:/srv/project
            - ~/.composer:/home/docker/.composer
        working_dir: /srv/project
