version: 2.1

executors:
  php_8_1:
    docker:
      - image: cimg/php:8.1-browsers
  php_8_2:
    docker:
      - image: cimg/php:8.2-browsers

jobs:
  build:
    parameters:
      php_executor:
        type: executor

    executor: << parameters.php_executor >>

    working_directory: ~/repo

    steps:
      - run: sudo docker-php-ext-install sockets

      - checkout

      - run: composer install -n --prefer-dist

      - persist_to_workspace:
          root: ~/repo
          paths:
            - vendor
  tests:
    parameters:
      php_executor:
        type: executor

    executor: << parameters.php_executor >>

    working_directory: ~/repo

    steps:
      - run: sudo docker-php-ext-install sockets

      - checkout

      - attach_workspace:
          at: ~/repo

      - run: composer dump -o
      - run:
          name: CS Fixer
          command: ./vendor/bin/php-cs-fixer fix --config=.php_cs.php --diff --dry-run -v
      - run:
          name: PhpStan
          command: ./vendor/bin/phpstan analyse src --level 5
      - run:
          name: Unit tests
          command: ./vendor/bin/phpunit tests/Unit/
      - run:
          name: Integration tests
          command: ./vendor/bin/phpunit tests/Integration/

workflows:
  version: 2
  build_test:
    jobs:
      - build:
          matrix:
            parameters:
              php_executor: [ 'php_8_1', 'php_8_2' ]
      - tests:
          matrix:
            parameters:
              php_executor: [ 'php_8_1', 'php_8_2' ]
          requires:
            - build
