version: 2
jobs:
    build:
        docker:
            -   image: circleci/php:7.2-browsers

        working_directory: ~/repo

        steps:
            - run:
                    name: Disable XDebug
                    command: sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

            - run: sudo docker-php-ext-install sockets

            - checkout

            - run: composer install -n --prefer-dist

            - persist_to_workspace:
                    root: ~/repo
                    paths:
                        - vendor
    tests:
        docker:
            -   image: circleci/php:7.2-browsers

        working_directory: ~/repo

        steps:
            - run:
                  name: Disable XDebug
                  command: sudo sed -i 's/^zend_extension/;zend_extension/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

            - run: sudo docker-php-ext-install sockets

            - checkout

            -   attach_workspace:
                    at: ~/repo

            -   run: composer dump -o
            -   run:
                    name: CS Fixer
                    command: ./vendor/bin/php-cs-fixer fix --config=.php_cs.php --diff --dry-run -v
            -   run:
                    name: Unit tests
                    command: ./vendor/bin/phpunit tests/Unit/
            -   run:
                    name: Integration tests
                    command: ./vendor/bin/phpunit tests/Integration/

workflows:
    version: 2
    build_test:
        jobs:
            - build
            - tests:
                  requires:
                      - build
